version: '3.4'

services:

  api:
    image: node:12.16.1
    container_name: 'api'
    restart: always
    volumes:
      - ./../:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      API_PORT: 3000
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: admin
      DATABASE_NAME: atendimentos
    ports:
      - 3000:3000
      - 9229:9229
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm run debug'

  db:
    image: mysql:5.7
    container_name: 'db'
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: atendimentos
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
